npm i @openzeppelin/contracts-upgradeable@latest \
  @openzeppelin/hardhat-upgrades@latest \
  @openzeppelin/test-helpers@latest \
  @openzeppelin/contracts@latest \
  @uniswap/v2-core@latest \
  @uniswap/v2-periphery@latest \
  @uniswap/v3-core@latest \
  @uniswap/v3-periphery@latest \
  web3@latest \
  dotenv@latest \
  @truffle/hdwallet-provider@latest \
  @typechain/ethers-v5@latest \
  @nomiclabs/hardhat-waffle@latest \
  @nomiclabs/hardhat-ethers@latest \
  ganache-core@latest \
  hardhat@latest \
  keythereum@latest \
  truffle-plugin-verify@latest \
  @nomiclabs/hardhat-etherscan@latest \
  @types/jest@latest \
  @types/mocha@latest \
  @typechain/hardhat@latest \
  chai@latest \
  eth-gas-reporter@latest \
  hardhat-contract-sizer@latest \
  hardhat-gas-reporter@latest \
  ts-node@latest \
  typescript@latest --force
